config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :categories, except: [:show]
  resources :clients, except: [:show]
  resources :suppliers, except: [:show]
  resources :products, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, length: {minimum:11, maximum:255}

  has_many :products, dependent: :destroy

  scope :descendent, -> { order(created_at: :desc) }
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales

  validates :total_name, presence: true

  scope :descendent, -> { order(created_at: :desc) }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true 
  belongs_to :supplier
  has_many :warehouse_records
  
  mount_uploader :image, PhotoProductUploader

end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  belongs_to :user
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
  has_many :warehouse_records

  scope :descendent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :sales       
  has_many :warehouse_records       
end

app/models/warehouse_record.rb
class WarehouseRecord < ApplicationRecord
  belongs_to :supplier
  belongs_to :product
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  layout :layout_by_resource
  
  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]
  
  def index
    @categories = Category.descendent
  end

  def new
    @category = Category.new
  end
  
  def create
    # byebug
    @category = Category.new(category_params)

     respond_to do |format|
      # format.js { render template: 'categories/create2.js.erb' }
      if @category.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @category.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @category.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end
  
  def destroy
    @category.destroy
    respond_to do |format|
      format.json { respond :no_content }
      format.js 
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end  

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:edit, :update, :destroy]

  def index
    @clients = Client.descendent
  end

  def new 
    @client = Client.new
  end

  def create 
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @client.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @client.update(client_params)
        format.json {head :no_content}
        format.js
      else
        format.json { render json: @client.error.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @client.destroy
    respond_to do |format|
      format.js
      format.json { respond :no_content }
    end
  end

  def buscador
    @resultados = Client.buscador(params[:termino]).map do |cliente|
      {
        id: cliente.id,
        nombre_cliente: cliente.nombre
      }
    end

    respond_to do |format|
      format.json { render :json => @resultados }
    end
  end

  private 
  
  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:total_name, :address, :phone_number)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit, :create]
  before_action :set_suppliers, only: [:new, :edit, :create]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    # byebug
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.json {head :no_content}
        format.js
      else
        format.json { render json: @product.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @product.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  def buscador
    @resultados = Product.buscador(params[:termino]).map do |producto|
      {
        id: producto.id,
        nombre_producto: producto.nombre,
        existencia: producto.existencia
      }
    end

    respond_to do |format|
      format.json { render json: @resultados }
    end
  end

  private
  
  def product_params
    params.require(:product).permit(:image, :name, :description, :existence, :price, :category_id, :supplier_id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def set_suppliers
    @suppliers = Supplier.all
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:edit, :update, :destroy]

  def index
    @suppliers = Supplier.descendent
  end

  def new
    @supplier = Supplier.new
  end

  def edit
  end

  def create
    @supplier = Supplier.new(supplier_params)
    
    respond_to do |format|
      if @supplier.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @supplier.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @supplier.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @supplier.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:total_name, :address, :phone_number)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_category.html.erb
<tr id="category_<%= category.id %>" >
  <td><%= category.name %></td>
  <td><%= category.description %></td>
  <td>
    <%# <button class= "btn btn-info" data-toggle="modal" data-target="#exampleModal">Editar</button> %>
    <%= link_to 'Editar', edit_category_path(category), id: 'editCategory', class: 'btn btn-info', remote: true %>
    <%= link_to 'Borrar', category, method: :delete, remote: true, class: 'btn btn-danger', data: {confirm: "are you sure? #{category.name}"} %>
  </td>
</tr>

<%= render 'modal' %>

app/views/categories/_form.html.erb
<%= form_with(model: @category, remote: true) do |form| %>
  <div class="form-group">
    <h4 class="control-label">Datos de la categor&iacute;a:</h4>
  </div>

  <div class="item form-group<%= @category.errors[:name].any? ? 'has-error has-feedback' : '' %>">
    <%= form.label :name, "Nombre de la categoría:" %>
    <div class="input-group">
      <%= form.text_field :name, class:"form-control", placeholder: "" %>
      <% if @category.errors[:name].any? %>
        <p class="bg-danger"><%= @category.errors[:name].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @category.errors[:description].any? ? 'has-error has-feedback' : '' %>">
    <%= form.label :description, "Descripción de la categoría:" %>
    <div class="input-group">
      <%= form.text_area :description, class:"form-control", placeholder: "" %>
      <% if @category.errors[:description].any? %>
        <p class="bg-danger"><%= @category.errors[:description].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <%= form.submit @category.new_record? ? "Crear Categoría" : "Actualizar Categoría", :class => "btn btn-success"%>
<% end %>

app/views/categories/_id_category.html.erb
<tr id="category_<%= @category.id %>">
  <td><%= @category.name %></td>
  <td><%= @category.description %></td>
  <td>
    <%= link_to 'Editar', edit_category_path(@category), remote: true, class: "btn btn-info" %>
    <%= link_to 'Borrar', @category, method: :delete, remote: true, class: 'btn btn-danger', data: {confirm: "are you sure? #{@category.name}"} %>
  </td>
</tr>

app/views/categories/_modal.html.erb
<div class="modal fade" id="modalCategory" tabindex="-1" role="dialog" aria-labelledby="modalCategoryLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-category-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body-category modal-body" id="modal-body-category">

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/categories/create.js.erb
$('#modalCategory').modal('toggle');
$('#dataTable').prepend('<%= j render("id_category")%>');

app/views/categories/destroy.js.erb
$('#category_<%= @category.id %>').fadeOut();

app/views/categories/edit.js.erb
// Add the dialog title
$('#modal-category-title').html("Editar categor&iacute;a");

// Render the new form
$('.modal-body-category').html('<%= j render("form")%>');

// Show the dynamic dialog
$('#modalCategory').modal('show');

app/views/categories/index.html.erb
<h3 class="h3 mb-2 text-gray-800">Categor&iacute;as de productos</h3>

<%= link_to new_category_path, remote: true, class: "btn btn-info mb-3" do %>
  <span class="fas fa-plus-square"></span>
<% end %>

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Nombre categor&iacute;a</th>
            <th>Descripci&oacute;n categor&iacute;a</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <%= render @categories %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal' %>

app/views/categories/new.js.erb
// Add the dialog title
$('#modal-category-title').html("Nueva categor&iacute;a");

// Render the new form
$('.modal-body-category').html('<%= j render("form")%>');

// Show the dynamic dialog
$('#modalCategory').modal('show');

app/views/categories/update.js.erb
$('#modalCategory').modal('toggle');
$('#category_<%= @category.id %>').replaceWith('<%= j render("id_category")%>');

app/views/clients/_client.html.erb
<tr id="client_<%= client.id %>" >
  <td><%= client.total_name %></td>
  <td><%= client.address %></td>
  <td><%= client.phone_number %></td>
  <td>
    <%= link_to "Editar", edit_client_path(client), class: "btn btn-info", remote: true %>
    <%= link_to "Borrar", client, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{client.total_name}?"}, class: "btn btn-danger" %>
  </td>
</tr>

app/views/clients/_form.html.erb
<%= form_with(model: @client, remote: true) do |form| %>
  <div class="form-group">
    <h4 class="control-label">Datos del cliente</h4>
  </div>

  <div class="item form-group<%= @client.errors[:total_name].any? ? 'has-error has-feedback' : '' %>">
    <%= form.label :total_name, "Nombre del cliente:" %>
    <div class="input-group">
      <%= form.text_field :total_name, class:"form-control", placeholder: "" %>
      <% if @client.errors[:total_name].any? %>
        <p class="bg-danger"><%= @client.errors[:total_name].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @client.errors[:address].any? ? 'has-error has-feedback' : '' %>">
    <%= form.label :address, "Dirección del cliente:" %>
    <div class="input-group">
      <%= form.text_field :address, class:"form-control", placeholder: "" %>
      <% if @client.errors[:address].any? %>
        <p class="bg-danger"><%= @client.errors[:address].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @client.errors[:phone_number].any? ? 'has-error has-feedback' : '' %>">
    <%= form.label :phone_number, "Número de telefono:" %>
    <div class="input-group">
      <%= form.text_field :phone_number, class:"form-control", placeholder: "" %>
      <% if @client.errors[:phone_number].any? %>
        <p class="bg-danger"><%= @client.errors[:phone_number].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <%= form.submit @client.new_record? ? "Nuevo Cliente" : "Actualizar Cliente", :class => "btn btn-success"%>
<% end %>

app/views/clients/_id_client.html.erb
<tr id="client_<%= @client.id %>">
  <td><%= @client.total_name %></td>
  <td><%= @client.address %></td>
  <td><%= @client.phone_number %></td>
  <td>
    <%= link_to 'Editar', edit_client_path(@client), remote: true, class: "btn btn-info" %>
    <%= link_to 'Borrar', @client, method: :delete, remote: true, class: 'btn btn-danger', data: {confirm: "are you sure? #{@client.total_name}"} %>
  </td>
</tr>

app/views/clients/_modal_client.html.erb
<div class="modal fade" id="modalClient" tabindex="-1" role="dialog" aria-labelledby="modalClientLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-client-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body-client modal-body" id="modal-body-client">

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/clients/create.js.erb
$('#modalClient').modal('toggle');
$('#dataTable').prepend('<%= j render("id_client")%>');

app/views/clients/destroy.js.erb
$('#client_<%= @client.id %>').fadeOut();

app/views/clients/edit.js.erb
$('#modal-client-title').html('Editar Cliente')

$('.modal-body-client').html('<%= j render("form")%>');

$('#modalClient').modal('show');

app/views/clients/index.html.erb
<h3 class="h3 mb-2 text-gray-800">Clientes</h3>

<%= link_to new_client_path, remote: true, class: "btn btn-info mb-3" do %>
  <span class="fas fa-plus-square"></span>
<% end %>

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Direcci&oacute;n</th>
            <th>Tel&eacute;fono</th>
            <th>Acciones</th>
          </tr>
        </thead>

        <tbody>
          <%= render @clients %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render "modal_client" %>

app/views/clients/new.js.erb
$('#modal-client-title').html('Nuevo Cliente')

$('.modal-body-client').html('<%= j render("form")%>');

$('#modalClient').modal('show');

app/views/clients/update.js.erb
$('#modalClient').modal('toggle');
$('#client_<%= @client.id %>').replaceWith('<%= j render("id_client")%>');

app/views/layouts/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="index.html">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Interface
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Components</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Custom Components:</h6>
        <a class="collapse-item" href="buttons.html">Buttons</a>
        <%= link_to  "Clientes", clients_path, class: "collapse-item" %>
        <%= link_to  "Categorias", categories_path, class: "collapse-item" %>
        <%= link_to  "Proveedores", suppliers_path, class: "collapse-item" %>
        <%= link_to  "Productos", products_path, class: "collapse-item" %>
      </div>
    </div>
  </li>

  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Utilities</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Custom Utilities:</h6>
        <a class="collapse-item" href="utilities-color.html">Colors</a>
        <a class="collapse-item" href="utilities-border.html">Borders</a>
        <a class="collapse-item" href="utilities-animation.html">Animations</a>
        <a class="collapse-item" href="utilities-other.html">Other</a>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Addons
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
      <i class="fas fa-fw fa-folder"></i>
      <span>Pages</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Login Screens:</h6>
        <a class="collapse-item" href="login.html">Login</a>
        <a class="collapse-item" href="register.html">Register</a>
        <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
        <div class="collapse-divider"></div>
        <h6 class="collapse-header">Other Pages:</h6>
        <a class="collapse-item" href="404.html">404 Page</a>
        <a class="collapse-item" href="blank.html">Blank Page</a>
      </div>
    </div>
  </li>

  <!-- Nav Item - Charts -->
  <li class="nav-item">
    <a class="nav-link" href="charts.html">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Charts</span></a>
  </li>

  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a class="nav-link" href="tables.html">
      <i class="fas fa-fw fa-table"></i>
      <span>Tables</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'sb-admin-2.min' %>

  </head>
  <%# <p class="notice"><%= notice %>
  <%# <p class="alert"><%= alert %>

  <body id="page-top">
    <div id="wrapper">
      <!-- Sidebar -->
      <%= render 'layouts/sidebar' %>
      <!-- End of Sidebar -->
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
              <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
              <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                  </button>
                </div>
              </div>
            </form>

            <!-- Topbar Navbar -->
            <%= render 'layouts/navbar' %>
          </nav>
          <!-- End of Topbar -->
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/products/_modal_products.html.erb
<div class="modal fade" id="modalProduct" tabindex="-1" role="dialog" aria-labelledby="modalProductLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-product-title">Modal title</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body-product modal-body" id="modal-body-product">

      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<tr id="product_<%= product.id %>" >
  <td><%= image_tag(product.image.url, size: "50x50", class: "rounded-circle") if product.image? %></td>
  <td><%= product.name %></td>
  <td><%= product.existence %></td>
  <td>$<%= product.price %></td>
  <td><%= product.category ? product.category.name : "No tiene categoria" %></td>
  <td><%= product.supplier ? product.supplier.total_name : "No tiene proveedor" %></td>
  <td>
    <%= link_to "Editar", edit_product_path(product), class: "btn btn-info" , remote: true %>
    <%= link_to "Borrar", product, remote: true, method: :delete, data: { confirm: "¿Borrar producto: #{product.name}?"}, class: "btn btn-danger" %>
  </td>
</tr>

app/views/products/create.js.erb
$('#modalProduct').modal('toggle');
$('#dataTable').prepend('<%= j render("product", product: @product)%>');

app/views/products/index.html.erb
<h1 class="h3 mb-2 text-gray-800">Productos</h1>

<div>
  <%= link_to new_product_path, { remote: true, class: "btn btn-info mb-3" }  do %>
    <span class="fas fa-plus-square" ></span>
  <% end %>
</div>

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th></th>
            <th>Nombre producto</th>
            <th>Existencia</th>
            <th>Precio</th>
            <th>Categor&iacute;a</th>
            <th>Proveedor</th>
            <th>Acci&oacute;n</th>
          </tr>
        </thead>

        <tbody>
          <%= render @products %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_products' %>

app/views/suppliers/_id_supplier.html.erb
<tr id="supplier_<%= @supplier.id %>">
  <td><%= @supplier.total_name %></td>
  <td><%= @supplier.address %></td>
  <td><%= @supplier.phone_number %></td>
  <td>
    <%= link_to 'Editar', edit_supplier_path(@supplier), remote: true, class: "btn btn-info" %>
    <%= link_to 'Borrar', @supplier, method: :delete, remote: true, class: 'btn btn-danger', data: {confirm: "are you sure? #{@supplier.total_name}"} %>
  </td>
</tr>

app/views/suppliers/_supplier.html.erb
<tr id="supplier_<%= supplier.id %>" >
  <td><%= supplier.total_name %></td>
  <td><%= supplier.address %></td>
  <td><%= supplier.phone_number %></td>
  <td>
    <%= link_to "Editar", edit_supplier_path(supplier), class: "btn btn-info", remote: true %>
    <%= link_to "Borrar", supplier, remote: true, method: :delete, data: { confirm: "¿Borrar suppliere: #{supplier.total_name}?"}, class: "btn btn-danger" %>
  </td>
</tr>

app/views/suppliers/index.html.erb
<h1 class="h3 mb-2 text-gray-800">Proveedores</h1>

<div>
  <%= link_to new_supplier_path, remote: true, class: "btn btn-info mb-3", id: "addSupplier"  do %>
    <span class="fas fa-plus-square"></span>
  <%end%>
</div>

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Direcci&oacute;n</th>
            <th>Tel&eacute;fono</th>
            <th>Acciones</th>
          </tr>
        </thead>

        <tbody>

          <% @suppliers.each do |supplier| %>
            <p><%= supplier.total_name %></p>
            <p><%= supplier.address %></p>
            <p><%= supplier.phone_number %></p>
          <% end %>

          <%= render @suppliers %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_supplier' %>